# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build_java:
    docker:
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/openjdk:8-jdk
      # working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: gradle build javadoc fatjar # jmh - Disabling JMH as it's very unreliable under CircleCI
      - run: .circleci/save_artifacts.sh
      - run: .circleci/push_gh_pages.sh

      - store_test_results:
          path: ~/tests

      - store_artifacts:
          path: ~/artifacts

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}


  build_android:

      #working_directory: ~/code
      docker:
        - image: thedrhax/android-sdk
        #//https://github.com/thedrhax-dockerfiles/android-sdk


      environment:
            JVM_OPTS: -Xmx3200m
            ANDROID_HOME: /home/user/android-sdk-linux
            BUILD_ENV : circle_ci

      steps:

        - checkout

        - restore_cache:
            keys:
            - v1-dependencies-{{ checksum "./keyple-example/android/nfc/build.gradle" }}

        #assemble keyple core and calypso
        - run:
            name: Assemble Keyple
            command:  gradle build

        #Download NFC project dependencies
        - run:
            name: Download Dependencies for Example Android NFC
            command: gradle -b ./keyple-example/android/nfc/build.gradle androidDependencies

        #Download OMAPI project dependencies
        - run:
            name: Download Dependencies for Example Android OMAPI
            command: gradle -b ./keyple-example/android/omapi/build.gradle androidDependencies

        #Save dependencies in cache
        - save_cache:
            paths:
              - ~/.gradle
            key: v1-dependencies-{{ checksum "./keyple-example/android/nfc/build.gradle" }}

        #Assemble Plugin NFC
        - run:
            name: Assemble Plugin NFC plugin to aar file
            command: gradle -b ./keyple-plugins/android-nfc/build.gradle assembleDebug generateDebugJavadoc

        #Assemble Example App NFC
        - run:
            name: Assemble Keyple Example Android NFC application to apk file
            command: gradle -b ./keyple-example/android/nfc/build.gradle assembleDebug

        #Assemble Plugin OMAPI
        - run:
            name: Assemble Plugin OMAPI plugin to aar file
            command: gradle -b ./keyple-plugins/android-omapi/build.gradle assembleCircle_ci generateDebugJavadoc

        #Assemble Example App OMAPI
        - run:
            name: Assemble Keyple Example Android OMAPI application to apk file
            command: gradle -b ./keyple-example/android/omapi/build.gradle assembleCircle_ci

        #store Example App NFC
        - store_artifacts:
            path: ./keyple-example/android/nfc/build/outputs/apk/debug
            destination: keyple-example/android/nfc/

        #store Example App OMAPI
        - store_artifacts:
            path: ./keyple-example/android/omapi/build/outputs/apk/debug
            destination: keyple-example/android/omapi/

        #store Plugin NFC
        - store_artifacts:
            path: ./keyple-plugins/android-nfc/build/outputs/aar/
            destination: keyple-plugins/android-nfc/

        #store Plugin OMAPI
        - store_artifacts:
            path: ./keyple-plugins/android-omapi/build/outputs/aar/
            destination: keyple-plugins/android-omapi/


workflows:
  version: 2
  java_and_android_build:
    jobs:
      - build_java
      - build_android
