# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build_java:
    docker:
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/openjdk:8-jdk
      # working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: gradle build javadoc fatjar # jmh - Disabling JMH as it's very unreliable under CircleCI
      - run: .circleci/save_artifacts.sh
      - run: .circleci/push_gh_pages.sh

      - store_test_results:
          path: ~/tests

      - store_artifacts:
          path: ~/artifacts

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}


  build_android:

      #working_directory: ~/code
      docker:
        - image: thedrhax/android-sdk
        #//https://github.com/thedrhax-dockerfiles/android-sdk


      environment:
            JVM_OPTS: -Xmx3200m

      steps:

        - checkout

        - restore_cache:
            keys:
            - v1-dependencies-{{ checksum "./keyple-example-android-nfc/build.gradle" }}

        - run:
            name: Assemble Keyple
            command: ANDROID_HOME=/home/user/android-sdk-linux gradle build

        - run:
            name: Download Dependencies
            command: ANDROID_HOME=/home/user/android-sdk-linux gradle -b ./keyple-example-android-nfc/build.gradle androidDependencies

        - save_cache:
            paths:
              - ~/.gradle
            key: v1-dependencies-{{ checksum "./keyple-example-android-nfc/build.gradle" }}

        - run:
            name: Assemble Plugin NFC plugin to aar file
            command: ANDROID_HOME=/home/user/android-sdk-linux gradle -b ./keyple-plugin-android-nfc/build.gradle assembleDebug generateDebugJavadoc

        - run:
            name: Assemble Keyple Example Android NFC application to apk file
            command: ANDROID_HOME=/home/user/android-sdk-linux gradle -b ./keyple-example-android-nfc/build.gradle assembleDebug


        - store_artifacts:
              path: ./keyple-example-android-nfc/build/outputs/apk/debug
              destination: keyple-example-android-nfc/

        - store_artifacts:
              path: ./keyple-plugin-android-nfc/build/outputs/aar/
              destination: keyple-plugin-android-nfc/


workflows:
  version: 2
  java_and_android_build:
    jobs:
      - build_java
      - build_android
